version: '3.8'

services:
  # Serviço para o Django
  web:
    build: .
    container_name: django-api
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/DJANGO_API
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
